version: "3"

services:
  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ../postgresql/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
